### ISSUE TITLE
leadership board not showing correct information

### ISSUE THREAD

**Issue by nicolehli** [startupstorm/bc-hacktoberfest#2]
First page of leadership board is not showing the right image and PR number for the very bottom user. It's duplicating the image and PR value of the user above it.

![capture](https://user-images.githubusercontent.com/17561746/31565325-3a26ba26-b01b-11e7-80ff-e0b138f78e6a.PNG)

**Comment by chamkank** [comment]
Thanks for reporting this - it's no longer there but it looks like it happens during some of the leaderboard updates. Not quite sure what's going on but I'll look into it!

**Comment by chamkank** [comment]
I've figured out the issue - turns out GitHub was blocking calls to its API because of rate limiting, so I've increased the timeout to 20 seconds (meaning we now wait 20 seconds between each user update on the leaderboard). 

Commit: https://github.com/startupstorm/bc-hacktoberfest/commit/6e2e79f34393e333599054865e022d5aba0657f6

Thanks again for letting me know!
